// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/signer.proto

package signer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 幂等/防重放
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// 业务单据（验真用）
	WithdrawId string `protobuf:"bytes,2,opt,name=withdraw_id,json=withdrawId,proto3" json:"withdraw_id,omitempty"`
	// 链与资金要素（policy+验真用）
	Chain       string `protobuf:"bytes,3,opt,name=chain,proto3" json:"chain,omitempty"`
	FromAddress string `protobuf:"bytes,4,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress   string `protobuf:"bytes,5,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Amount      string `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"` // wei, decimal string
	// 交易载荷（Signer 只签这个，不构造）
	UnsignedTx []byte `protobuf:"bytes,7,opt,name=unsigned_tx,json=unsignedTx,proto3" json:"unsigned_tx,omitempty"` // RLP of unsigned tx (go-ethereum MarshalBinary)
	// 授权验真（HMAC）
	AuthToken string `protobuf:"bytes,8,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"` // hex(HMAC-SHA256)
	// 调用方身份（审计用）
	Caller        string `protobuf:"bytes,9,opt,name=caller,proto3" json:"caller,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_proto_signer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_proto_signer_proto_rawDescGZIP(), []int{0}
}

func (x *SignRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SignRequest) GetWithdrawId() string {
	if x != nil {
		return x.WithdrawId
	}
	return ""
}

func (x *SignRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *SignRequest) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *SignRequest) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *SignRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *SignRequest) GetUnsignedTx() []byte {
	if x != nil {
		return x.UnsignedTx
	}
	return nil
}

func (x *SignRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *SignRequest) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

type SignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignedTx      []byte                 `protobuf:"bytes,1,opt,name=signed_tx,json=signedTx,proto3" json:"signed_tx,omitempty"` // RLP of signed tx
	TxHash        string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`       // optional: signer can compute after signing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_proto_signer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_proto_signer_proto_rawDescGZIP(), []int{1}
}

func (x *SignResponse) GetSignedTx() []byte {
	if x != nil {
		return x.SignedTx
	}
	return nil
}

func (x *SignResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type DeriveAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         string                 `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeriveAddressRequest) Reset() {
	*x = DeriveAddressRequest{}
	mi := &file_proto_signer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeriveAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeriveAddressRequest) ProtoMessage() {}

func (x *DeriveAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeriveAddressRequest.ProtoReflect.Descriptor instead.
func (*DeriveAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_signer_proto_rawDescGZIP(), []int{2}
}

func (x *DeriveAddressRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *DeriveAddressRequest) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type DeriveAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeriveAddressResponse) Reset() {
	*x = DeriveAddressResponse{}
	mi := &file_proto_signer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeriveAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeriveAddressResponse) ProtoMessage() {}

func (x *DeriveAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeriveAddressResponse.ProtoReflect.Descriptor instead.
func (*DeriveAddressResponse) Descriptor() ([]byte, []int) {
	return file_proto_signer_proto_rawDescGZIP(), []int{3}
}

func (x *DeriveAddressResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_proto_signer_proto protoreflect.FileDescriptor

const file_proto_signer_proto_rawDesc = "" +
	"\n" +
	"\x12proto/signer.proto\x12\x06signer\"\x95\x02\n" +
	"\vSignRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vwithdraw_id\x18\x02 \x01(\tR\n" +
	"withdrawId\x12\x14\n" +
	"\x05chain\x18\x03 \x01(\tR\x05chain\x12!\n" +
	"\ffrom_address\x18\x04 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x05 \x01(\tR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\tR\x06amount\x12\x1f\n" +
	"\vunsigned_tx\x18\a \x01(\fR\n" +
	"unsignedTx\x12\x1d\n" +
	"\n" +
	"auth_token\x18\b \x01(\tR\tauthToken\x12\x16\n" +
	"\x06caller\x18\t \x01(\tR\x06caller\"D\n" +
	"\fSignResponse\x12\x1b\n" +
	"\tsigned_tx\x18\x01 \x01(\fR\bsignedTx\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\"B\n" +
	"\x14DeriveAddressRequest\x12\x14\n" +
	"\x05chain\x18\x01 \x01(\tR\x05chain\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\"1\n" +
	"\x15DeriveAddressResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress2\x9b\x01\n" +
	"\rSignerService\x12<\n" +
	"\x0fSignTransaction\x12\x13.signer.SignRequest\x1a\x14.signer.SignResponse\x12L\n" +
	"\rDeriveAddress\x12\x1c.signer.DeriveAddressRequest\x1a\x1d.signer.DeriveAddressResponseB\x15Z\x13proto/signer;signerb\x06proto3"

var (
	file_proto_signer_proto_rawDescOnce sync.Once
	file_proto_signer_proto_rawDescData []byte
)

func file_proto_signer_proto_rawDescGZIP() []byte {
	file_proto_signer_proto_rawDescOnce.Do(func() {
		file_proto_signer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_signer_proto_rawDesc), len(file_proto_signer_proto_rawDesc)))
	})
	return file_proto_signer_proto_rawDescData
}

var file_proto_signer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_signer_proto_goTypes = []any{
	(*SignRequest)(nil),           // 0: signer.SignRequest
	(*SignResponse)(nil),          // 1: signer.SignResponse
	(*DeriveAddressRequest)(nil),  // 2: signer.DeriveAddressRequest
	(*DeriveAddressResponse)(nil), // 3: signer.DeriveAddressResponse
}
var file_proto_signer_proto_depIdxs = []int32{
	0, // 0: signer.SignerService.SignTransaction:input_type -> signer.SignRequest
	2, // 1: signer.SignerService.DeriveAddress:input_type -> signer.DeriveAddressRequest
	1, // 2: signer.SignerService.SignTransaction:output_type -> signer.SignResponse
	3, // 3: signer.SignerService.DeriveAddress:output_type -> signer.DeriveAddressResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_signer_proto_init() }
func file_proto_signer_proto_init() {
	if File_proto_signer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_signer_proto_rawDesc), len(file_proto_signer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_signer_proto_goTypes,
		DependencyIndexes: file_proto_signer_proto_depIdxs,
		MessageInfos:      file_proto_signer_proto_msgTypes,
	}.Build()
	File_proto_signer_proto = out.File
	file_proto_signer_proto_goTypes = nil
	file_proto_signer_proto_depIdxs = nil
}
