// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/withdraw.proto

package withdraw

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitBTCRBFRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	WithdrawId          string                 `protobuf:"bytes,1,opt,name=withdraw_id,json=withdrawId,proto3" json:"withdraw_id,omitempty"`
	OldTxHash           string                 `protobuf:"bytes,2,opt,name=old_tx_hash,json=oldTxHash,proto3" json:"old_tx_hash,omitempty"`
	FeeTargetBlocks     int64                  `protobuf:"varint,3,opt,name=fee_target_blocks,json=feeTargetBlocks,proto3" json:"fee_target_blocks,omitempty"`
	MinDeltaSatPerVbyte int64                  `protobuf:"varint,4,opt,name=min_delta_sat_per_vbyte,json=minDeltaSatPerVbyte,proto3" json:"min_delta_sat_per_vbyte,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SubmitBTCRBFRequest) Reset() {
	*x = SubmitBTCRBFRequest{}
	mi := &file_proto_withdraw_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitBTCRBFRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitBTCRBFRequest) ProtoMessage() {}

func (x *SubmitBTCRBFRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_withdraw_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitBTCRBFRequest.ProtoReflect.Descriptor instead.
func (*SubmitBTCRBFRequest) Descriptor() ([]byte, []int) {
	return file_proto_withdraw_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitBTCRBFRequest) GetWithdrawId() string {
	if x != nil {
		return x.WithdrawId
	}
	return ""
}

func (x *SubmitBTCRBFRequest) GetOldTxHash() string {
	if x != nil {
		return x.OldTxHash
	}
	return ""
}

func (x *SubmitBTCRBFRequest) GetFeeTargetBlocks() int64 {
	if x != nil {
		return x.FeeTargetBlocks
	}
	return 0
}

func (x *SubmitBTCRBFRequest) GetMinDeltaSatPerVbyte() int64 {
	if x != nil {
		return x.MinDeltaSatPerVbyte
	}
	return 0
}

type SubmitBTCRBFResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	WithdrawId            string                 `protobuf:"bytes,1,opt,name=withdraw_id,json=withdrawId,proto3" json:"withdraw_id,omitempty"`
	RequestId             string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status                string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	OldFeeRateSatPerVbyte int64                  `protobuf:"varint,4,opt,name=old_fee_rate_sat_per_vbyte,json=oldFeeRateSatPerVbyte,proto3" json:"old_fee_rate_sat_per_vbyte,omitempty"`
	NewFeeRateSatPerVbyte int64                  `protobuf:"varint,5,opt,name=new_fee_rate_sat_per_vbyte,json=newFeeRateSatPerVbyte,proto3" json:"new_fee_rate_sat_per_vbyte,omitempty"`
	OldFeeSat             int64                  `protobuf:"varint,6,opt,name=old_fee_sat,json=oldFeeSat,proto3" json:"old_fee_sat,omitempty"`
	NewFeeSat             int64                  `protobuf:"varint,7,opt,name=new_fee_sat,json=newFeeSat,proto3" json:"new_fee_sat,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SubmitBTCRBFResponse) Reset() {
	*x = SubmitBTCRBFResponse{}
	mi := &file_proto_withdraw_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitBTCRBFResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitBTCRBFResponse) ProtoMessage() {}

func (x *SubmitBTCRBFResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_withdraw_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitBTCRBFResponse.ProtoReflect.Descriptor instead.
func (*SubmitBTCRBFResponse) Descriptor() ([]byte, []int) {
	return file_proto_withdraw_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitBTCRBFResponse) GetWithdrawId() string {
	if x != nil {
		return x.WithdrawId
	}
	return ""
}

func (x *SubmitBTCRBFResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SubmitBTCRBFResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitBTCRBFResponse) GetOldFeeRateSatPerVbyte() int64 {
	if x != nil {
		return x.OldFeeRateSatPerVbyte
	}
	return 0
}

func (x *SubmitBTCRBFResponse) GetNewFeeRateSatPerVbyte() int64 {
	if x != nil {
		return x.NewFeeRateSatPerVbyte
	}
	return 0
}

func (x *SubmitBTCRBFResponse) GetOldFeeSat() int64 {
	if x != nil {
		return x.OldFeeSat
	}
	return 0
}

func (x *SubmitBTCRBFResponse) GetNewFeeSat() int64 {
	if x != nil {
		return x.NewFeeSat
	}
	return 0
}

var File_proto_withdraw_proto protoreflect.FileDescriptor

const file_proto_withdraw_proto_rawDesc = "" +
	"\n" +
	"\x14proto/withdraw.proto\x12\bwithdraw\"\xb8\x01\n" +
	"\x13SubmitBTCRBFRequest\x12\x1f\n" +
	"\vwithdraw_id\x18\x01 \x01(\tR\n" +
	"withdrawId\x12\x1e\n" +
	"\vold_tx_hash\x18\x02 \x01(\tR\toldTxHash\x12*\n" +
	"\x11fee_target_blocks\x18\x03 \x01(\x03R\x0ffeeTargetBlocks\x124\n" +
	"\x17min_delta_sat_per_vbyte\x18\x04 \x01(\x03R\x13minDeltaSatPerVbyte\"\xa4\x02\n" +
	"\x14SubmitBTCRBFResponse\x12\x1f\n" +
	"\vwithdraw_id\x18\x01 \x01(\tR\n" +
	"withdrawId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x129\n" +
	"\x1aold_fee_rate_sat_per_vbyte\x18\x04 \x01(\x03R\x15oldFeeRateSatPerVbyte\x129\n" +
	"\x1anew_fee_rate_sat_per_vbyte\x18\x05 \x01(\x03R\x15newFeeRateSatPerVbyte\x12\x1e\n" +
	"\vold_fee_sat\x18\x06 \x01(\x03R\toldFeeSat\x12\x1e\n" +
	"\vnew_fee_sat\x18\a \x01(\x03R\tnewFeeSat2`\n" +
	"\x0fWithdrawService\x12M\n" +
	"\fSubmitBTCRBF\x12\x1d.withdraw.SubmitBTCRBFRequest\x1a\x1e.withdraw.SubmitBTCRBFResponseB\x19Z\x17proto/withdraw;withdrawb\x06proto3"

var (
	file_proto_withdraw_proto_rawDescOnce sync.Once
	file_proto_withdraw_proto_rawDescData []byte
)

func file_proto_withdraw_proto_rawDescGZIP() []byte {
	file_proto_withdraw_proto_rawDescOnce.Do(func() {
		file_proto_withdraw_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_withdraw_proto_rawDesc), len(file_proto_withdraw_proto_rawDesc)))
	})
	return file_proto_withdraw_proto_rawDescData
}

var file_proto_withdraw_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_withdraw_proto_goTypes = []any{
	(*SubmitBTCRBFRequest)(nil),  // 0: withdraw.SubmitBTCRBFRequest
	(*SubmitBTCRBFResponse)(nil), // 1: withdraw.SubmitBTCRBFResponse
}
var file_proto_withdraw_proto_depIdxs = []int32{
	0, // 0: withdraw.WithdrawService.SubmitBTCRBF:input_type -> withdraw.SubmitBTCRBFRequest
	1, // 1: withdraw.WithdrawService.SubmitBTCRBF:output_type -> withdraw.SubmitBTCRBFResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_withdraw_proto_init() }
func file_proto_withdraw_proto_init() {
	if File_proto_withdraw_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_withdraw_proto_rawDesc), len(file_proto_withdraw_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_withdraw_proto_goTypes,
		DependencyIndexes: file_proto_withdraw_proto_depIdxs,
		MessageInfos:      file_proto_withdraw_proto_msgTypes,
	}.Build()
	File_proto_withdraw_proto = out.File
	file_proto_withdraw_proto_goTypes = nil
	file_proto_withdraw_proto_depIdxs = nil
}
