// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/withdraw.proto

package withdraw

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WithdrawService_SubmitRBF_FullMethodName   = "/withdraw.WithdrawService/SubmitRBF"
	WithdrawService_SubmitTopUp_FullMethodName = "/withdraw.WithdrawService/SubmitTopUp"
)

// WithdrawServiceClient is the client API for WithdrawService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WithdrawServiceClient interface {
	SubmitRBF(ctx context.Context, in *SubmitRBFRequest, opts ...grpc.CallOption) (*SubmitRBFResponse, error)
	SubmitTopUp(ctx context.Context, in *SubmitTopUpRequest, opts ...grpc.CallOption) (*SubmitTopUpResponse, error)
}

type withdrawServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWithdrawServiceClient(cc grpc.ClientConnInterface) WithdrawServiceClient {
	return &withdrawServiceClient{cc}
}

func (c *withdrawServiceClient) SubmitRBF(ctx context.Context, in *SubmitRBFRequest, opts ...grpc.CallOption) (*SubmitRBFResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitRBFResponse)
	err := c.cc.Invoke(ctx, WithdrawService_SubmitRBF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *withdrawServiceClient) SubmitTopUp(ctx context.Context, in *SubmitTopUpRequest, opts ...grpc.CallOption) (*SubmitTopUpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitTopUpResponse)
	err := c.cc.Invoke(ctx, WithdrawService_SubmitTopUp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WithdrawServiceServer is the server API for WithdrawService service.
// All implementations must embed UnimplementedWithdrawServiceServer
// for forward compatibility.
type WithdrawServiceServer interface {
	SubmitRBF(context.Context, *SubmitRBFRequest) (*SubmitRBFResponse, error)
	SubmitTopUp(context.Context, *SubmitTopUpRequest) (*SubmitTopUpResponse, error)
	mustEmbedUnimplementedWithdrawServiceServer()
}

// UnimplementedWithdrawServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWithdrawServiceServer struct{}

func (UnimplementedWithdrawServiceServer) SubmitRBF(context.Context, *SubmitRBFRequest) (*SubmitRBFResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitRBF not implemented")
}
func (UnimplementedWithdrawServiceServer) SubmitTopUp(context.Context, *SubmitTopUpRequest) (*SubmitTopUpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTopUp not implemented")
}
func (UnimplementedWithdrawServiceServer) mustEmbedUnimplementedWithdrawServiceServer() {}
func (UnimplementedWithdrawServiceServer) testEmbeddedByValue()                         {}

// UnsafeWithdrawServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WithdrawServiceServer will
// result in compilation errors.
type UnsafeWithdrawServiceServer interface {
	mustEmbedUnimplementedWithdrawServiceServer()
}

func RegisterWithdrawServiceServer(s grpc.ServiceRegistrar, srv WithdrawServiceServer) {
	// If the following call panics, it indicates UnimplementedWithdrawServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WithdrawService_ServiceDesc, srv)
}

func _WithdrawService_SubmitRBF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRBFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawServiceServer).SubmitRBF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WithdrawService_SubmitRBF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawServiceServer).SubmitRBF(ctx, req.(*SubmitRBFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WithdrawService_SubmitTopUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTopUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawServiceServer).SubmitTopUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WithdrawService_SubmitTopUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawServiceServer).SubmitTopUp(ctx, req.(*SubmitTopUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WithdrawService_ServiceDesc is the grpc.ServiceDesc for WithdrawService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WithdrawService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "withdraw.WithdrawService",
	HandlerType: (*WithdrawServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitRBF",
			Handler:    _WithdrawService_SubmitRBF_Handler,
		},
		{
			MethodName: "SubmitTopUp",
			Handler:    _WithdrawService_SubmitTopUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/withdraw.proto",
}
